export const data = [
    { name: 'John Doe', email: 'john.doe@example.com' },
    { name: 'Jane Smith', email: 'jane.smith@example.com' },
    { name: 'Alice Johnson', email: 'alice.johnson@example.com' },
    { name: 'Bob Wilson', email: 'bob.wilson@example.com' },
    { name: 'Eva Martinez', email: 'eva.martinez@example.com' },
    { name: 'Michael Anderson', email: 'michael.anderson@example.com' },
    { name: 'Sophia Brown', email: 'sophia.brown@example.com' },
    { name: 'William Taylor', email: 'william.taylor@example.com' },
    { name: 'Olivia White', email: 'olivia.white@example.com' },
    { name: 'Daniel Harris', email: 'daniel.harris@example.com' },
    { name: 'Ava Thompson', email: 'ava.thompson@example.com' },
    { name: 'Matthew Miller', email: 'matthew.miller@example.com' },
    { name: 'Emma Davis', email: 'emma.davis@example.com' },
    { name: 'Liam Garcia', email: 'liam.garcia@example.com' },
    { name: 'Isabella Rodriguez', email: 'isabella.rodriguez@example.com' },
    { name: 'Mason Moore', email: 'mason.moore@example.com' },
    { name: 'Sophie Wilson', email: 'sophie.wilson@example.com' },
    { name: 'Logan Hall', email: 'logan.hall@example.com' },
    { name: 'Amelia Clark', email: 'amelia.clark@example.com' },
    { name: 'Ethan Turner', email: 'ethan.turner@example.com' },
];
